name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Display multiple lines secret
        run: |
          echo "atb" > test_file
          echo ${{ secrets.MULTIPLE_LINES }} >> test_file
          cat test_file
