name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Display multiple lines secret
        shell: bash
        env:
          MULTIPLE_LINES: ${{ secrets.MULTIPLE_LINES }}
        run: |
          echo "atb $MULTIPLE_LINES" > test_file
          cat test_file
